;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        backward-sexp
        cua-copy-region
        cua-delete-region
        cua-paste
        cua-paste-pop
        dabbrev-expand
        forward-sentence
        forward-sexp
        highlight-symbol-next
        iy-go-to-char
        iy-go-to-char-backward
        mark-whole-line
        org-self-insert-command
        sgml-close-tag
        sgml-slash
        tab-to-tab-stop
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        cua-cut-region
        dired-copy-filename-as-kill
        eval-expression
        smex
        yaml-electric-dash-and-dot
        my-create-fake-cursor
        ))
