;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        backward-sexp
        cua-copy-region
        cua-delete-region
        cua-exchange-point-and-mark
        cua-paste
        cua-paste-pop
        dabbrev-expand
        delete-indentation
        forward-sentence
        forward-sexp
        highlight-symbol-next
        indent-for-tab-command
        iy-go-to-char
        iy-go-to-char-backward
        jedi:dot-complete
        mark-whole-line
        org-self-insert-command
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        sgml-close-tag
        sgml-slash
        sp--self-insert-command
        tab-to-tab-stop
        transpose-words
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        cua-cut-region
        dired-copy-filename-as-kill
        eval-expression
        my-create-fake-cursor
        smex
        toggle-truncate-lines
        yaml-electric-dash-and-dot
        ))
