;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        backward-sexp
        coffee-dedent-line-backspace
        cua-copy-region
        cua-delete-region
        cua-exchange-point-and-mark
        cua-paste
        cua-paste-pop
        cua-set-rectangle-mark
        dabbrev-expand
        delete-indentation
        duplicate-line
        forward-sentence
        forward-sexp
        highlight-symbol-next
        indent-for-tab-command
        insert-date
        iy-go-to-char
        iy-go-to-char--command
        iy-go-to-char-backward
        jade-comment-dwim
        jedi:dot-complete
        mark-whole-line
        org-self-insert-command
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        sgml-close-tag
        sgml-slash
        sp--cua-replace-region
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        tab-to-tab-stop
        transpose-symbols
        transpose-words
        upcase-region
        wdired-set-bit
        wgrep-finish-edit
        yaml-electric-backspace
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        cua-cut-region
        dired-copy-filename-as-kill
        eval-expression
        iflipb-next-buffer
        my-create-fake-cursor
        overwrite-mode
        save-some-buffers
        smex
        toggle-truncate-lines
        yaml-electric-dash-and-dot
        ))
