(require 'fold-dwim)
(global-set-key (kbd "<f9>") 'fold-dwim-toggle)
(global-set-key (kbd "<S-f9>") 'fold-dwim-hide-all)
(global-set-key (kbd "<C-f9>") 'fold-dwim-show-all)
(provide 'setup-fold-dwim)
